---
title: "ThinkLab CCC Survey Response Processing"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages and utils

```{r load, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
source("utils.R")
```

Load the csv of survey results and reshape it, only keeping the quantitative questions

```{r process}
survey_path <- "survey_responses/ThinkLab CCC_ Survey for the Museums.csv"
n_questions <- paste0(c(rep(1, 6), rep(2, 7)), ".", c(1:6, 1:7))
df <- read.csv(survey_path) %>%
  responses_reformat()
```

Create faceted histograms of answers, as well as a histogram per question

```{r histograms}
histogram_faceted(df)
for(qn in n_questions){
  print(histogram_individual(df, questions = qn))
}
```

Compare questions (the pairs can be modified)

```{r comparisons, message = FALSE}
n_questions <- paste0(c(rep(1, 6), rep(2, 7)), ".", c(1:6, 1:7))
pairs <- rbind(expand.grid(n_questions[1:6], n_questions[1:6]),
               expand.grid(n_questions[7:13], n_questions[7:13])) %>%
  mutate(v2 = as.numeric(as.character(Var2)), v1 = as.numeric(as.character(Var1))) %>%
  filter(v1 > v2) %>%
  select(Var2, Var1)

for(i in seq_len(nrow(pairs))){
  f <- unlist(pairs[i, ])
  print(pair_plot(df, pair = levels(f)[f]))
}
```

